### ISSUE TITLE
Supported NFC readers / chip reader

### ISSUE THREAD

**Issue by kradecki** [Infineon/Blockchain#5]
1. Is there a supported NFC reader list available? 
2. Can you use the built-in chipset to notarize the data?

**Comment by miguelpincheira** [comment]
I would also like to know about that list, particularly with readers compatible with microcontrollers.

**Comment by WaltherPachler** [comment]
Sorry for that late response: 
Well, i would say any reader ;)! However, if you want to make it work with our libraries, there is a list of readers that can be connected via USB (pyscard):
https://ccid.apdu.fr/select_readers/?features=contactless

**Comment by WaltherPachler** [comment]
@kradecki  - could you explain the 2nd point a little more

**Comment by kradecki** [comment]
The card has an NFC chip and a Physical Chip. we can sign transactions using the NFC chip, but the physical metal chip is not usable. I wonder what is it for.

**Comment by WaltherPachler** [comment]
The starter kit as it is supports NFC only. Howevery, it is possible to have - in a volume request - the ISO7816 also active - if requested. Certainly the starter kit is just a starting point.
